title: "Laravel入門 - Laravelを使ってみよう!"
summary: "
PHPフレームワークは Laravel と CakePHP で人気を2分していました。


今では Laravel が一歩リードしていて主流となっていています。  


Laravel がスタンダードの地位を獲得するのも時間の問題のように思われます。  


この書籍は そんな Laravel を習得してみたいという方のためのものです。 
また、環境構築には Docker を使用するので手早く開発を体験することもできます。 


題材の「タスクリスト（To Do List）」のアプリケーションの開発を通してフレームワークとはどんなものか実際に手を動かして学んでいきましょう。
" # 本の紹介文
topics: ["PHP", "Laravel", "Docker", "初心者"] # タグ
published: true # 公開設定
price: 0 # 有料の場合200〜5000
toc_depth: 3 # 目次設定0~3で指定
# 本に含めるチャプターを順番に並べましょう
chapters: