title: "Laravel入門 - Laravelを使ってみよう!"
summary: "
昨今ではPHPの性能向上に伴ってLaravelがスタンダードの地位を獲得しました。

PHPフレームワークは Laravel と CakePHP で人気を2分していましたが、今ではLaravelが主流となっています。

この書籍は そんなLaravelを習得してみたいという方のためのBOOKになっています。
" # 本の紹介文
topics: ["PHP", "Laravel", "初心者"] # タグ
published: true # 公開設定
price: 0 # 有料の場合200〜5000
toc_depth: 3 # 目次設定0~3で指定
# 本に含めるチャプターを順番に並べましょう
chapters: